export const validators = {
  username_IS_EMPTY: 'username_IS_EMPTY',
  PASSWORD_IS_EMPTY: 'PASSWORD_IS_EMPTY',
  PASSWORD_LENGTH_MUST_BE_MORE_THAN_8: 'PASSWORD_LENGTH_MUST_BE_MORE_THAN_8',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  SOME_THING_WENT_WRONG: 'SOME_THING_WENT_WRONG',
  USER_EXISTS_ALREADY: 'USER_EXISTS_ALREADY',
  USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
  TOKEN_IS_EMPTY: 'TOKEN_IS_EMPTY',
  username_IS_IN_WRONG_FORMAT: 'username_IS_IN_WRONG_FORMAT',
  ROLE_DOES_NOT_EXIST: 'ROLE_DOES_NOT_EXIST',
  ROLE_IS_EMPTY: 'ROLE_IS_EMPTY',
  ROLE_IS_NOT_VALID: 'ROLE_IS_NOT_VALID',
  INVALID_username_AND_PASSWORD: 'INVALID_username_AND_PASSWORD',
  ROLE_MUST_BE_STRING_TYPE: 'ROLE_MUST_BE_STRING_TYPE',
  ROLE_MUST_BE_FLOAT_TYPE: 'ROLE_MUST_BE_FLOAT_TYPE',
  ROLE_MUST_BE_ARRAY_TYPE: 'ROLE_MUST_BE_ARRAY_TYPE',
  ROLE_MUST_BE_INTEGER_TYPE: 'ROLE_MUST_BE_INTEGER_TYPE',
  ROLE_MUST_BE_DATE_TYPE: 'ROLE_MUST_BE_DATE_TYPE',
  ROLE_MUST_BE_OBJECT_TYPE: 'ROLE_MUST_BE_OBJECT_TYPE'
}

export const message = {
  LOGIN_SUCCESS: 'User login successfully!',
  LOGIN_FAILED: 'Login failed!',
  REGISTER_SUCCESS: 'User register successfully!',
  REGISTER_FAILED: 'Register failed!',
  SUCCESS: 'Success!',
  FAILED: 'Failed!',
  ERROR: 'Error!',
  CREATED: 'Created!',
  UPDATED: 'Updated!',
  DELETED: 'Deleted!',
  CREATION_FAILED: 'Creation failed!',
  UPDATE_FAILED: 'Update failed!',
  DELETE_FAILED: 'Delete failed!',
  NOT_FOUND: 'Not found!'
}
